[project]
name = "crafting-interpreters"
version = "0.1.0"
description = "An interpreter for the Lox language, written in Python"
requires-python = ">=3.12"
dependencies = [
    "pre-commit>=4.2.0",
]
